const imageArray = [
    'https://tom.imgix.net/artsy/1.jpg',
    'https://tom.imgix.net/artsy/2.jpg',
    'https://tom.imgix.net/artsy/3.jpg',
    'https://tom.imgix.net/artsy/4.jpg',
    'https://tom.imgix.net/artsy/5.jpg',
    'https://tom.imgix.net/artsy/6.jpg',
    'https://tom.imgix.net/artsy/7.jpg',
    'https://tom.imgix.net/artsy/8.jpg',
    'https://tom.imgix.net/artsy/9.jpg',
    'https://tom.imgix.net/artsy/10.jpg',
    'https://tom.imgix.net/artsy/11.jpg',
    'https://tom.imgix.net/artsy/12.jpg',
    'https://tom.imgix.net/artsy/13.jpg',
    'https://tom.imgix.net/artsy/1.jpg',
    'https://tom.imgix.net/artsy/2.jpg',
    'https://tom.imgix.net/artsy/3.jpg',
    'https://tom.imgix.net/artsy/4.jpg',
    'https://tom.imgix.net/artsy/5.jpg',
    'https://tom.imgix.net/artsy/6.jpg',
    'https://tom.imgix.net/artsy/7.jpg',
    'https://tom.imgix.net/artsy/8.jpg',
    'https://tom.imgix.net/artsy/9.jpg',
    'https://tom.imgix.net/artsy/10.jpg',
    'https://tom.imgix.net/artsy/11.jpg',
    'https://tom.imgix.net/artsy/12.jpg',
    'https://tom.imgix.net/artsy/13.jpg'
  ];

export default imageArray;
