const imageArray = [
    'https://tom.imgix.net/artsy/1.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/2.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/3.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/4.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/5.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/6.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/7.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/8.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/9.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/10.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/11.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/12.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/13.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/1.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/2.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/3.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/4.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/5.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/6.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/7.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/8.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/9.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/10.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/11.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/12.jpg?w=600&h=600&fit=crop&auto=format,compress',
    'https://tom.imgix.net/artsy/13.jpg?w=600&h=600&fit=crop&auto=format,compress'
  ];

export default imageArray;
